### ISSUE TITLE
Vragen

### ISSUE THREAD

**Issue by remb0** [jodur/ESPEASY_Plugin_ITHO#1]
Allereerst hartelijk dank voor je werk! ik zou dit graag willen nabouwen en gebruiken in mijn domoticz systeem
maar ik heb nog enkele vragen waar jij hopelijk antwoord op kunt geven

kan je misschien wat screenshots plaatsen?
en een foto van welke chip en hoe jij hem hebt aangesloten?

want dat kan ik dat nabouwen en zijn mijn settings als:
1st gpio pin correct

Wellicht handig om te beschrijven op de readme hoe je aan een remote ID komt.

send to controller? is that a idx of domoticz a virtual selector?

Voorheen had ik een itho knop aan mijn nodemcu gemaakt en gebruikte ik links als:
http://192.168.0.63/control?cmd=GPIO1.1
zal dat nu zo gaan:
http://192.168.0.63/control?cmd=1111

https://dutch.alibaba.com/product-detail/cc1101-wireless-868mhz-module-long-range-transceiver-module-60625007607.html?spm=a2700.8699010.29.8.69082b8an0r7l6&s=p
Is nu de chip dit ik gebruik, dit lijkt me correct. ik krijg alleen nergens de chip gevonden met normale pin headers of mogelijkheid om jumpercables te gebruiken

**Comment by jodur** [comment]
> kan je misschien wat screenshots plaatsen?
> en een foto van welke chip en hoe jij hem hebt aangesloten?
> 

Als je het tweakers topic doorleest kom je genoeg fotos tegen hoe de C1101 is aangesloten. Als je tweaker genoeg bent moet je er met mijn aanwijzingen uitkomen, anders kun je er beter mee stoppen.

> Wellicht handig om te beschrijven op de readme hoe je aan een remote ID komt.

Als je de readme goed had gelezen staat daar precies in hoe he het ID van je remote kan achterhalen.

> send to controller? is that a idx of domoticz a virtual selector?

Geef geen support op domoticz of algemene ESP_Easy vragen. 
Alleen vragen m.b.t. plugin aub.

Lees het Topic van Begin tot eind maar eens door, dan zijn heel veel vragen al beantwoord. Dit heb ik ook gedaan.
