### ISSUE TITLE
Add some info about calling the esp to the readme.md

### ISSUE THREAD

**Issue by nldroid** [jodur/ESPEASY_Plugin_ITHO#2]
First of all: Thanks for the great work. It was easy to add this to my ESPEasy and control my Itho fan with it.

What would help is if you add some info on how to 'pair' the ESP (remove power plug, wait 15 seonds, insert power plug, pair within 2 minutes) or point to the manual. I don't have a 'real' remote so i've never paired before.

It took me a while to figure out how to call the ESP using MQTT. The thread on tweakers.net gives some misleading information. Maybe you can add a line to the readme.md on how to use it.

**Comment by jodur** [comment]
I will add some info about it, however the purpose of this plugin was never to provide an "lazy" way to implement the control of the fan with ESP8286. You have to put some "effort" in it and afterwards the reward is a working remote controlled fan.  ;)

**Comment by nldroid** [comment]
Fair enough :)

I was just suggesting because you have some examples for using it through http but not for MQTT.

If you want, i can create a pull request, add some text and let you merge it.

Edit: you already added it :)

Edit2: I never got it to work with the MQTT command line you documented. I need to use it like this:

mosquitto_pub -h 192.168.86.110 -t /ventilator/**cmd -m 'state 1'**

With the -h pointing to a remote Mosquito but the relevant part is the cmd with the parameter.

**Comment by jodur** [comment]
You are right my info regarding MQTT was not correct (typed to fast)

it should be: mosquitto_pub -t /Fan/cmd -m 'state 1'

**Comment by nldroid** [comment]
That was exactly the reason why it took me a while before it worked :) I've read the tweakers.net thread but the examples given there were confusing.

I've mentioned your project here: https://community.home-assistant.io/t/ventilation-based-on-co2-levels/37383/2 b.t.w.
