### ISSUE TITLE
Minor bug in Remote ID matching

### ISSUE THREAD

**Issue by jvanderzande** [jodur/ESPEASY_Plugin_ITHO#4]
Hi, 
I have used your source to build my own version and noticed that the check for remote ID 3 is wrong and also pointing to ID2. I wanted to make a pull request but my editor also automatically fixes some formatting and didn't want to bother you with that. :-) 

Line 448:   else if (rfremoteid == PLUGIN_145_ExtraSettings.**ID2**) return 3;

Thanks for sharing the code.
Jos

**Comment by jodur** [comment]
Thnx for pointing out the typo bug. Made a new commit with the fix.
