### ISSUE TITLE
NRF905 support?

### ISSUE THREAD

**Issue by zuidwijk** [jodur/ESPEASY_Plugin_ITHO#8]
Hi, I've got a nrf905 module, which has more connectors, yet seems to miss the GDO0 and GDO2 pins. Is this module usable?

It has the ports:
VCC (check)
TXEN
TRXCE
PW_UP
UPLK
CD
AM
DR
MISO (check)
MOSI (check)
SCK (check)
CSN (check)
GND (check)

**Comment by zuidwijk** [comment]
Small bump ;-) Any support?

**Comment by jodur** [comment]
No code is based on c1101 module as you could read in readme. For other chipset you have to create your own. The c1101 is only a few bug on alieexpress so i would suggest in following that path.

**Comment by zuidwijk** [comment]
Ok! I already got the CC1101, yet also the nrf905, so wanted to give it a chance :-)
